# Retinoblastoma and Cancer Cell Metabolism

This week's tutorial has *seven* short answer questions to answer:

## Question 1

> How is the activity of Retinoblastoma (i.e., Rb) regulated during the cell cycle?

Rb is regulated via a series of phosphorylations by MAP kinases during the M phase of the cell cycle.  When Rb is unphosphorylated, it binds to the transcription cofactor E2F (only when another protein called "DP" is present) to inhibit transcription.

However, during mitosis, mitogens cause a regulatory protein p16 to unbind a kinase subunit called "CDK4".  CDK4 then binds to another subunit called "Cyclin D" to form a CDK4 / Cyclin D complex - this behaves as a kinase.

This complex then goes on to phosphorylate Rb - this, in turn, causes Rb to disassociate with E2F and allowing gene transcription.

## Question 2

> Briefly how Rb was found in a mouse cell extract.

Retinoblastoma is the name of a rare cancer of the retina cells (i.e., the cells of the eye responsible for detecting colors) that often occurs during childhood - about one in 20000 children below the age of five end up with this.

Scientists looked into this matter using mice as subjects.  They knocked out (i.e., removed) certain genes from the mice to induce the formation of a retinoblastoma.  When they performed genomic sequencing on the mice, they found that the mice were missing a gene on their 13^th^ chromosome - hence the discovery of the Rb gene.

## Question 3

> Design an experiment that can be used to find the transactivation domain of the Rb protein.


## Question 4

> Explain how phosphorylation regulates Rb's binding with E2F and DP

If we examine the transactivation domain of Rb, we find that there are multiple phosphorylation sites near the said domain.  Nonetheless, when this portion of the Rb protein is phosphorylated, the loop folds back in on the Rb protein and binds to the B subdomain - this forms several positive ionic interactions and displaces the HDAC protein - a protein that inhibits gene transcription.

## Question 5

> Explain the Warburg effect in cancerous cells.  Why do cancer cells use aerobic glycolysis?

The Warburg effect refers to the phenomenon whereby cancerous cells generate ATP via non-oxidiative means (i.e., not the TCA cycle) using pyruvate in order to proliferate and grow.

Cancerous cells do use aerobic metabolism to grow and to proliferate, but this is uncommon.  Proliferating cells have a high ratio of ATP to ADP, and an enzyme calle adenylate kinase converts two ADP molecules into ATP and AMP.  This elevated AMP amount in the cell then activates AMPK - an activity that is dependent on the tumor suppressor protein LKB1.  LKB1 also leads to the phosphorylation of multiple targets and hence, a change in energy needs of the cell.

## Question 6

> Explain the PI3K / Akt / mTOR pathway and the role(s) it plays in the metabolism of cancer cells.

The provided pathway is a master regulator of aerobic glycolysis in cells.  The Akt protein in the pathway increases lactate production and glycolysis: both activities that cancer cells use to proliferate and grow.

## Question 7

> Explain how the PTEN phosphatase and its mutants behave as tumor suppressants.

The PTEN phosphatase is an inhibitor of the AKt protein; it makes it so that Akt is unable to perform glycolysis and lactate production.

