# Oncometabolites, Ras, and IDH

## Question 1

> Explain the molecular basis of oncometabolite production from the R132H mutant of IDH1.

The R132H mutant in isocitrate dehydrogenase-1 makes it so that IDH1 is unable to form ionic bonds between the ICT portion of itself and the rest of itself.  Because of this, a substance called $\alpha$-ketoglutarate is transformed into something called R-2-HG while also consuming NADPH that's generated by wild type IDH1 (which takes $\alpha$-ketoglutarate and transforms it into isocitrate and reduces NADP^+^ to NADPH). This R-2-HG then goes to inhibit proteins that belong to the $\alpha$-ketoglutarate dependent dioxygenase family of proteins.

When an R132H mutation happens, this makes it so that IDH1's closed form is continuously favored, hence R132H IDH1's affinity for $\alpha$-ketoglutarate and NADPH.

## Question 2

> Explain the types of post translation modifications Ras protein undergoes. Why are these modifications necessary?

There are several things that can happen with the Ras protein:

1.  **Adding farnesyl pyrophosphate to Ras** 

    This is a reaction catalyzed by an enzyme called farnesyltransferase (i.e., Ftase).  This addition basically stabilizes Ras in the cell's membranes.
    
1.  **Adding palmitoyl to the C-terminus of Ras' cysteine residue**

    This is a reaction catalyzed by an emzyme called palmitoyltransferase - this basically also helps stabilize Ras in the cell's membranes.
    
1.  **Phosphorylation**

    Phosphorylation makes it so that Ras is able to switch between its active and its inactive form.
    
## Question 3

> Genetic studies on drosophila eye development have helped in establishing Ras signaling pathway. In a screening assay for R7 phenotype was appeared to identify two groups of flies; one group contains mutation in the boss gene (UV blind) whereas another group has mutation in ras gene, producing hyperactive Ras protein (not blind to UV). An FYP student became interested to examine these mutant flies whereby crossing was conducted between these groups. 
>
> Explain the phenotype of R7 one may probably observed in the offspring flies.

There could be one of several outcomes.  Granted - we don't know the inheritance pattern of these mutations in the sev gene, but we can still guess several outcomes:

1.  **The offspring are UV blind too**

    If the mutation for the R8 gene (which makes the BOSS protein) is autosomal dominant, this could very well overshadow the hyperactive sev gene mutation.
    
    Also, BOSS is crucial for proper functioning of the sev-TRK.  Without BOSS, there wouldn't be anything to induce the development of R7 photoreceptor cells.
    
1.  **The offspring have overactive Ras mutations, but this won't affect vision per se**

    Researchers have already found out that an overactive Ras can still induce the development of the R7 photoreceptor cell even in the absence of the Sev gene or the BOSS protein.
    
    So, while the flies' visions may be unaffected, an overactive Ras protein could still trigger unwanted downstream signalling in other pathways.
    
## Question 4

> "Describe an in vivo assay that can be used to detect time course of Ras activation."

I would first covalently attach the fluorescent protein RFP to GTP molecules.  I would then transfect these GTP molecules into cells with Ras that's been covalently coupled with YFP (i.e., another fluorescent protein).  I would then make a FRET plot when I introduce the GTP into the cell to measure the light intensity.

The graph should go up before it comes down - kinda like a parabola.  The width of the parabola is how long Ras activation lasts.

## Question 5

> How does GEF facilitate nucleotide exchange in Ras?

GEF exchanges GDP in Ras for GTP, thereby also activating the Ras protein in the process.

GEF basically interacts with inactive Ras through its inactive domain - this GEF and Ras-GDP (i.e., inactive Ras) complex is stable and induces a sort of conformational change, hence also increasing Ras' affinity for GTP.

GTP then binds to the nucleotide-binding pocket of Ras, GDP is released, and the GEF disassociates.

## Question 6

> Why is Ras a slow GTPase? How does GAP help in stimulating GTPase activity of Ras?

Ras is slow because the rate of GTP hydrolysis in Ras isn't very fast.  

However, GAP encourages GTP hydrolysis and hence inactivates the Ras protein.  GAP induces a sort of conformational change in Ras such that GTP hydrolysis occurs easier.  

## Question 7

> Explain molecular mechanism of G12R Ras in cancer.

This is a mutated form of Ras that basically keeps it active all the time.  In this form, glycine is replaced by arginine at position 12, and this prevents GTP hydrolysis.  Because of this, Ras is allowed to activate downstream pathways - including those that are involved in cell growth, cell proliferation.

## Question 8

> Q61L mutant bind to GAP but still maintains oncogenic activity. Explain.

This is because GTP hydrolysis is reduced - there's a conformational form that prevents this from happening that well.  Because of this, stuff like the MAPK, mTOR / PI3K / AKT pathways keep being activated.